# Generated by Django 6.0 on 2025-12-26 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='操作执行的时间', verbose_name='操作时间')),
                ('operation_type', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], db_index=True, help_text='操作的类型：CREATE/UPDATE/DELETE', max_length=20, verbose_name='操作类型')),
                ('content_type', models.CharField(db_index=True, help_text='被操作对象的模型，格式：app_label.ModelName', max_length=255, verbose_name='模型标识')),
                ('object_id', models.CharField(db_index=True, help_text='被操作对象的主键ID', max_length=255, verbose_name='对象ID')),
                ('old_values', models.JSONField(blank=True, help_text='对象修改前的数据，JSON格式', null=True, verbose_name='修改前的值')),
                ('new_values', models.JSONField(blank=True, help_text='对象修改后的数据，JSON格式', null=True, verbose_name='修改后的值')),
                ('operator', models.ForeignKey(blank=True, help_text='执行此操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-operate_time'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='operation_l_content_8807b9_idx'), models.Index(fields=['operator', 'operate_time'], name='operation_l_operato_e4e094_idx')],
            },
        ),
    ]
