version: '3.1'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: fs_project
      MYSQL_USER: fs_project
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
